wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.5
    start_time: 1677378866.019998
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 7
      - 23
      4: 3.8.5
      5: 0.13.10
      6: 4.19.2
      8:
      - 5
